#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path("../../lib", __FILE__)

require 'ruby-cli' # require all files by this

arg = ARGV[0]

if arg == "-v"
  puts "v#{RubyCLI::VERSION}"
elsif arg == "-h"
  puts "ruby-cli PROJECT_NAME"
else
  RubyCLI::Setup.execute(arg)
end
